spring.application.name=cloudchat-backend

# MongoDB Atlas connection (replace with your actual connection string!)
# Replace <password> with the password you set
spring.mongodb.uri=mongodb+srv://aaryakulkarni2025c_db_user:Basic12345@cluster0-cloudchat.ptpy3dg.mongodb.net/cloudchat?appName=Cluster0-cloudchat
# Server port
server.port=8080

# Logging level (use DEBUG during development)
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.cloudchat=DEBUG